{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "dir_a/good.m",
        "kind": "file",
        "line": 3
      },
      "name": "good",
      "refs": [],
      "shared": true,
      "tag": "matlab good"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
