{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "collection/lib_a/wibble.m",
        "kind": "file",
        "line": 3
      },
      "name": "wibble",
      "refs": [],
      "shared": false,
      "tag": "matlab wibble"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "collection/lib_b/wobble.m",
        "kind": "file",
        "line": 3
      },
      "name": "wobble",
      "refs": [],
      "shared": false,
      "tag": "matlab wobble"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "my_library/+potato/fun.m",
        "kind": "file",
        "line": 3
      },
      "name": "fun",
      "refs": [],
      "shared": false,
      "tag": "matlab potato.fun"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "other_library/+potato/fun.m",
        "kind": "file",
        "line": 3
      },
      "name": "fun",
      "refs": [],
      "shared": false,
      "tag": "matlab potato.fun"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "other_library/+potato/sad.m",
        "kind": "file",
        "line": 3
      },
      "name": "sad",
      "refs": [],
      "shared": false,
      "tag": "matlab potato.sad"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
