{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "foo.m",
        "kind": "file",
        "line": 1
      },
      "name": "foo",
      "refs": [
        "req basic.potato"
      ],
      "shared": false,
      "tag": "matlab foo"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "test.slx",
        "kind": "file",
        "line": 1
      },
      "name": "fcn",
      "refs": [],
      "shared": false,
      "tag": "matlab test/Potato/Thing_A"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "test.slx",
        "kind": "file",
        "line": 1
      },
      "name": "fcn",
      "refs": [
        "req foo.bar"
      ],
      "shared": false,
      "tag": "matlab test/Potato/Thing_B"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "test.slx",
        "kind": "file",
        "line": null
      },
      "name": "test",
      "refs": [],
      "shared": false,
      "tag": "simulink test"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "test.slx",
        "kind": "file",
        "line": null
      },
      "name": "test/Potato",
      "refs": [],
      "shared": false,
      "tag": "simulink test/Potato"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
