{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "area.slx",
        "kind": "file",
        "line": null
      },
      "name": "area",
      "refs": [
        "req example.do_nothing"
      ],
      "shared": false,
      "tag": "simulink area"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
