{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "ep/potato.m",
        "kind": "file",
        "line": 1
      },
      "name": "potato",
      "refs": [],
      "shared": false,
      "tag": "matlab potato"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "lib_a/foo.m",
        "kind": "file",
        "line": 1
      },
      "name": "foo",
      "refs": [
        "req footag"
      ],
      "shared": true,
      "tag": "matlab foo"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "lib_b/bar.m",
        "kind": "file",
        "line": 1
      },
      "name": "bar",
      "refs": [
        "req bartag"
      ],
      "shared": true,
      "tag": "matlab bar"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
