{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "test.slx",
        "kind": "file",
        "line": null
      },
      "name": "test",
      "refs": [
        "req example.Requirement_Name",
        "req example.Another_Requirement"
      ],
      "shared": false,
      "tag": "simulink test"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
