{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 21,
        "file": "Potato.m",
        "kind": "file",
        "line": 6
      },
      "name": "Potato::method_a",
      "refs": [
        "req OK"
      ],
      "shared": false,
      "tag": "matlab Potato::method_a"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
