{
  "data": [
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagClassTest.m",
        "kind": "file",
        "line": 6
      },
      "name": "ExampleTagClassTest::testF",
      "refs": [
        "req FeatureB"
      ],
      "status": null,
      "tag": "matlab ExampleTagClassTest::testF"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagClassTest.m",
        "kind": "file",
        "line": 11
      },
      "name": "ExampleTagClassTest::testG",
      "refs": [
        "req FeatureB",
        "req FeatureC",
        "req System"
      ],
      "status": null,
      "tag": "matlab ExampleTagClassTest::testG"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagClassTest.m",
        "kind": "file",
        "line": 16
      },
      "name": "ExampleTagClassTest::testH",
      "refs": [
        "req FeatureA",
        "req FeatureB",
        "req System"
      ],
      "status": null,
      "tag": "matlab ExampleTagClassTest::testH"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagTest.m",
        "kind": "file",
        "line": 5
      },
      "name": "ExampleTagTest::testA",
      "refs": [],
      "status": null,
      "tag": "matlab ExampleTagTest::testA"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagTest.m",
        "kind": "file",
        "line": 10
      },
      "name": "ExampleTagTest::testB",
      "refs": [
        "req Unit"
      ],
      "status": null,
      "tag": "matlab ExampleTagTest::testB"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagTest.m",
        "kind": "file",
        "line": 13
      },
      "name": "ExampleTagTest::testC",
      "refs": [
        "req Unit"
      ],
      "status": null,
      "tag": "matlab ExampleTagTest::testC"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagTest.m",
        "kind": "file",
        "line": 18
      },
      "name": "ExampleTagTest::testD",
      "refs": [
        "req FeatureA",
        "req Unit"
      ],
      "status": null,
      "tag": "matlab ExampleTagTest::testD"
    },
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "ExampleTagTest.m",
        "kind": "file",
        "line": 23
      },
      "name": "ExampleTagTest::testE",
      "refs": [
        "req FeatureA",
        "req System"
      ],
      "status": null,
      "tag": "matlab ExampleTagTest::testE"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-act-trace",
  "version": 3
}
