{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 17,
        "file": "bar.m",
        "kind": "file",
        "line": 9
      },
      "name": "bar::inner",
      "refs": [
        "req kitten",
        "req potato",
        "req wibble"
      ],
      "shared": false,
      "tag": "matlab bar::inner"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "bar.m",
        "kind": "file",
        "line": 5
      },
      "name": "bar",
      "refs": [
        "req kitten",
        "req potato"
      ],
      "shared": false,
      "tag": "matlab bar"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "foo.m",
        "kind": "file",
        "line": 1
      },
      "name": "foo",
      "refs": [
        "req FeatureA"
      ],
      "shared": false,
      "tag": "matlab foo"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
