{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "test_1.slx",
        "kind": "file",
        "line": 1
      },
      "name": "First Subsystem/MATLAB Function",
      "refs": [],
      "shared": false,
      "tag": "matlab First Subsystem/MATLAB Function"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "test_1.slx",
        "kind": "file",
        "line": 1
      },
      "name": "Second Subsystem/MATLAB Function",
      "refs": [],
      "shared": false,
      "tag": "matlab Second Subsystem/MATLAB Function"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "test_1.slx",
        "kind": "file",
        "line": 1
      },
      "name": "Second Subsystem/MATLAB_Function",
      "refs": [],
      "shared": false,
      "tag": "matlab Second Subsystem/MATLAB_Function"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "test_1.slx",
        "kind": "file",
        "line": null
      },
      "name": "First Subsystem",
      "refs": [
        "req tag_b"
      ],
      "shared": false,
      "tag": "simulink First_Subsystem"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "test_1.slx",
        "kind": "file",
        "line": null
      },
      "name": "Second Subsystem",
      "refs": [
        "req tag_c"
      ],
      "shared": false,
      "tag": "simulink Second_Subsystem"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
