{
  "data": [
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 9,
        "file": "testing/my_test.m",
        "kind": "file",
        "line": 1
      },
      "name": "my_test",
      "refs": [],
      "status": null,
      "tag": "matlab my_test"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-act-trace",
  "version": 3
}
