{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 14,
        "file": "foo.m",
        "kind": "file",
        "line": 1
      },
      "name": "foo",
      "refs": [],
      "shared": false,
      "tag": "matlab foo"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
