{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "annotation_example.slx",
        "kind": "file",
        "line": null
      },
      "name": "annotation_example",
      "refs": [
        "req example.foo",
        "req secondexample.foo"
      ],
      "shared": false,
      "tag": "simulink annotation_example"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Block",
      "language": "Simulink",
      "location": {
        "column": null,
        "file": "annotation_example.slx",
        "kind": "file",
        "line": null
      },
      "name": "annotation_example/Subsystem",
      "refs": [
        "req example.foo",
        "req secondexample.foo"
      ],
      "shared": false,
      "tag": "simulink annotation_example/Subsystem"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
