{
  "data": [
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "matlab_2017b/cdef_subfun.m",
        "kind": "file",
        "line": 7
      },
      "name": "cdef_subfun.m::Potato",
      "refs": [],
      "shared": false,
      "tag": "matlab cdef_subfun.m::Potato"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "matlab_2017b/fun_contract.m",
        "kind": "file",
        "line": 3
      },
      "name": "fun_contract",
      "refs": [],
      "shared": false,
      "tag": "matlab fun_contract"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "matlab_2020b/cdef_subfun.m",
        "kind": "file",
        "line": 7
      },
      "name": "cdef_subfun.m::Potato",
      "refs": [],
      "shared": false,
      "tag": "matlab cdef_subfun.m::Potato"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "matlab_2020b/fun_contract.m",
        "kind": "file",
        "line": 3
      },
      "name": "fun_contract",
      "refs": [],
      "shared": false,
      "tag": "matlab fun_contract"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "matlab_2021a/cdef_subfun.m",
        "kind": "file",
        "line": 7
      },
      "name": "cdef_subfun.m::Potato",
      "refs": [],
      "shared": false,
      "tag": "matlab cdef_subfun.m::Potato"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 9,
        "file": "matlab_2021a/fun_contract.m",
        "kind": "file",
        "line": 3
      },
      "name": "fun_contract",
      "refs": [],
      "shared": false,
      "tag": "matlab fun_contract"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 14,
        "file": "octave_4_2/script_global.m",
        "kind": "file",
        "line": 5
      },
      "name": "script_global.m::Foo",
      "refs": [],
      "shared": false,
      "tag": "matlab script_global.m::Foo"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 13,
        "file": "octave_4_4/cdef_subfun.m",
        "kind": "file",
        "line": 7
      },
      "name": "cdef_subfun.m::Potato",
      "refs": [],
      "shared": false,
      "tag": "matlab cdef_subfun.m::Potato"
    },
    {
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Function",
      "language": "MATLAB",
      "location": {
        "column": 14,
        "file": "octave_4_4/script_global.m",
        "kind": "file",
        "line": 5
      },
      "name": "script_global.m::Foo",
      "refs": [],
      "shared": false,
      "tag": "matlab script_global.m::Foo"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-imp-trace",
  "version": 3
}
