{
  "data": [
    {
      "framework": "MATLAB",
      "just_down": [],
      "just_global": [],
      "just_up": [],
      "kind": "Test",
      "location": {
        "column": 17,
        "file": "test/TestPotato.m",
        "kind": "file",
        "line": 4
      },
      "name": "TestPotato::test_01",
      "refs": [
        "req Something"
      ],
      "status": null,
      "tag": "matlab TestPotato::test_01"
    }
  ],
  "generator": "MH Trace",
  "schema": "lobster-act-trace",
  "version": 3
}
